name: thesis
channels:
  - defaults
dependencies:
  - pip=20.0.2
  - python=3.7.7
  - setuptools=46.4.0
  - pip:
    - absl-py==0.9.0
    - appdirs==1.4.4
    - appnope==0.1.0
    - arcas==1.0.0
    - astor==0.8.1
    - attrs==19.3.0
    - axelrod==4.2.1
    - bibtexparser==1.2.0
    - black==19.10b0
    - blackbook==0.0.6
    - bleach==3.1.5
    - chardet==3.0.4
    - click==7.1.2
    - cloudpickle==1.4.1
    - coverage==5.1
    - cycler==0.10.0
    - dask==2.16.0
    - decorator==4.4.2
    - defusedxml==0.6.0
    - docopt==0.6.2
    - entrypoints==0.3
    - fsspec==0.7.4
    - future==0.18.2
    - gast==0.3.3
    - google-pasta==0.2.0
    - grpcio==1.29.0
    - h5py==2.10.0
    - idna==2.9
    - importlib-metadata==1.6.0
    - invoke==1.4.1
    - ipykernel==5.3.0
    - ipython==5.0.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - jinja2==2.11.2
    - joblib==0.14.1
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==6.1.3
    - jupyter-console==6.1.0
    - jupyter-core==4.6.3
    - keras==2.3.1
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - kiwisolver==1.2.0
    - loguru==0.5.0
    - markdown==3.2.2
    - markupsafe==1.1.1
    - matplotlib==3.2.1
    - mistune==0.8.4
    - more-itertools==8.3.0
    - mpmath==1.1.0
    - nbconvert==5.6.1
    - nbformat==5.0.6
    - notebook==6.0.3
    - numpy==1.15.4
    - packaging==20.4
    - pandas==1.0.3
    - pandocfilters==1.4.2
    - pathspec==0.8.0
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pluggy==0.13.1
    - prometheus-client==0.8.0
    - prompt-toolkit==1.0.18
    - protobuf==3.12.1
    - ptyprocess==0.6.0
    - py==1.8.1
    - pygments==2.6.1
    - pyparsing==2.4.7
    - pyrsistent==0.16.0
    - pytest==5.4.2
    - pytest-cov==2.9.0
    - python-dateutil==2.8.1
    - pytz==2020.1
    - pyyaml==5.3.1
    - pyzmq==19.0.1
    - qtconsole==4.7.4
    - qtpy==1.9.0
    - ratelimit==1.4.1
    - regex==2020.5.14
    - requests==2.23.0
    - requests-mock==1.8.0
    - scikit-learn==0.22.2.post1
    - scikit-optimize==0.5.2
    - scipy==1.4.1
    - send2trash==1.5.0
    - simplegeneric==0.8.1
    - six==1.15.0
    - sympy==1.2
    - tensorboard==1.14.0
    - tensorflow==1.14.0
    - tensorflow-estimator==1.14.0
    - termcolor==1.1.0
    - terminado==0.8.3
    - testpath==0.4.4
    - toml==0.10.1
    - toolz==0.10.0
    - tornado==6.0.4
    - tqdm==4.46.0
    - traitlets==4.3.3
    - typed-ast==1.4.1
    - urllib3==1.25.9
    - wcwidth==0.1.9
    - webencodings==0.5.1
    - werkzeug==1.0.1
    - widgetsnbextension==3.5.1
    - wrapt==1.12.1
    - zipp==3.1.0

